### ISSUE TITLE
Create Rspecs for Models

### ISSUE THREAD

**Issue by stanley-tarce** [stanley-tarce/stock-app#2]
Creating the following Models: 
1. User
2. Trader
3. Admin
4. Stocks * 
5. Market * 
6. Prices *

* Not yet final

**Comment by stanley-tarce** [comment]
[https://github.com/stanley-tarce/stock-app/commit/4506bf8b2eccacdc75bcafb9a21706dc5ef6f773#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55f](url) 
First Progress

**Comment by stanley-tarce** [comment]
Added Models

**Comment by stanley-tarce** [comment]
Need Rspecs for the following models: 
1. Markets
2. Stocks
3. Transaction History

**Comment by leandrajade** [comment]
completed: market model Rspecs
6a18352

**Comment by stanley-tarce** [comment]
Copy. Will check the file tonight

**Comment by leandrajade** [comment]
completed:

market & stock Rpecs:  e479f27
transaction_history Rpec:  4e09fb5

**Comment by stanley-tarce** [comment]
77f4023a92c5b5d8b7a81a6bac4032c0c5c60d90
