### ISSUE TITLE
Create Rspecs for Requests

### ISSUE THREAD

**Issue by stanley-tarce** [stanley-tarce/stock-app#4]
@leandrajade Please complete the following requests (Using the API routes)

1. Admin
User Story 1: As an Admin, I want to create a new user to manually add them to the app
User Story 2: As an Admin, I want to edit a specific user to update his/her details: fullname
User Story 3: As an Admin, I want to view a specific user to show his/her details: fullname, email
User Story 4: As an Admin, I want to see all the users that registered in the app so I can track all the users and approve/reject them
2. User
User Story 1: As a User, I want to create an account
User Story 2: As a User, I want to login my credentials so that I can access my account on the app
User Story 3: As a User, I want to receive an email after my registration to see if my registration is successful
User Story 4: As a User, I want to buy a stock from the stock market to add to my investment. Dropdown https://github.com/dblock/iex-ruby-client#get-symbols
User Story 5: As a User, I want to see my trading history
User Story 6: As a User, I want to receive an email to confirm my pending User Account signup. When admin approves my account
User Story 7: As a User, I want to sell the stocks I bought
User Story 8: As a User, I want to cash in (dummy)

1. User can buy and sell
2. Market stock prices are from iex-ruby-client (edited)

**Comment by leandrajade** [comment]
admin rspec
https://github.com/stanley-tarce/stock-app/commit/9fe3dd166606d2c1bba22c592d4ee36f151b7e0d

**Comment by leandrajade** [comment]
completed and updated format of markets_spec
 7616d4c

**Comment by leandrajade** [comment]
[completed and updated format of markets_spec](7616d4c) #4

**Comment by leandrajade** [comment]
#4 complete and updated format for markets  spec

**Comment by leandrajade** [comment]
[complete and updated format for markets spec](6f4a5ca) #4

**Comment by leandrajade** [comment]
complete and updated format for markets spec
6f4a5ca3e939c5072351e2c3223797cdaeff9d21

**Comment by stanley-tarce** [comment]
77f4023a92c5b5d8b7a81a6bac4032c0c5c60d90
