### ISSUE TITLE
PG::DuplicateTable: ERROR: relation "admins" already exists 

### ISSUE THREAD

**Issue by leandrajade** [stanley-tarce/stock-app#5]
there are pending migrations when I run rails s but whenever I try to migrate those, it gives me this error: 
![image](https://user-images.githubusercontent.com/30910148/146574489-3c8f2a31-0368-4edc-a98c-919d451cc0ea.png)

I found a solution from [here](https://stackoverflow.com/questions/14389841/devise-admin-role-pgerror-error-relation-admins-already-exists), but instead I got this response when I was trying to run db:drop.

![image](https://user-images.githubusercontent.com/30910148/146574660-4e6bf8bb-a1dd-4254-b057-6c2ffb7e3313.png)

I am not so sure yet why it is giving me "DETAIL:  There is 1 other  session using the database" and if it safe to proceed with dropping db as sol'n. Have you encounteredt this error as well?

**Comment by stanley-tarce** [comment]
rails db:drop db:create db:migrate 

You're trying to migrate a table that is already existing
Check if whether you are running the server in another console 
If not then it is free to recreate
